### ISSUE TITLE
Can we change the base map?

### ISSUE THREAD

**Issue by alex-x-sun** [tsinghua-fib-lab/DRL-urban-planning#6]
I was thinking if it is possible to change the base map to any road network. Is that possible? How did you process the base map (for example, dhm community) into geodataframe?

**Comment by DavyMorgan** [comment]
The codes can support any base map as long as it contains the polygons, lines, and points representing land blocks, road segments, and junctions. 

For now, the hlg and dhm maps are constructed manually according to the coordinates from OpenStreetMap. I think it would be better to develop a tool that can automatically transform the map from OSM to the format used in our model. However, it is not easy, since the data from OSM is much more complicated than the geodataframe in our code.

**Comment by alex-x-sun** [comment]
@DavyMorgan Thanks! If I try different basemaps, should I change the both pickle files in the test_data/real?

**Comment by DavyMorgan** [comment]
Yes, you can change the pickle files. I think it might be better to create a new folder in test_data/real.
